# Generated by Django 3.2.23 on 2025-11-18 08:55

import core.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0206_auto_20251113_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='comptaoperation',
            name='document',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage, upload_to=core.models.get_uuid_path, verbose_name='Pièce justificative'),
        ),
    ]
