# Generated by Django 3.2.23 on 2025-11-18 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0207_comptaoperation_document'),
        ('core', '0207_patch_article_null_constraint_fk_structure'),
    ]

    operations = [
    ]
