# Generated by Django 3.2.23 on 2025-12-09 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0209_auto_20251202_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='comptebancaire',
            name='bilan',
            field=models.BooleanField(default=True, verbose_name='Compte intégré au bilan'),
        ),
    ]
