# Generated by Django 3.2.23 on 2025-12-09 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0210_comptebancaire_bilan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comptebancaire',
            name='bilan',
        ),
        migrations.AddField(
            model_name='comptacategorie',
            name='bilan',
            field=models.BooleanField(default=True, verbose_name='Compte intégré au bilan'),
        ),
    ]
